## 
## Copyright (C) 2016-2017 by  Yuan Lufeng
## See license.txt for full license and copyright notice.
## 
## Authors: Yuan Lufeng 
## 
## test_single_timepoint_ProcessStack.py
## 
##  Created on: Oct 21th, 2016
##      Author: Yuan Lufeng 
## 
## \brief test single timepoint ProcessStack program generated by cython.
##
##
import _process_stack  


configFilename = "/home/tgmm/ylf/TBP-tgmm/data/TGMM_configFile_linux.txt"
parameterNum = 3
frame = 0 
basename = " "
radiusMedianFilter = 0
minTau = 0
backgroundThr = 0
conn3D = 0
print "configFilename: ",configFilename
print "parameterNum: ",parameterNum
print "frame: ",frame
error = _process_stack.ProcessStack_py(parameterNum, configFilename, frame)
#error, basename, radiusMedianFilter, minTau, backgroundThr, conn3D = _tgmm_io.readConfigFile_py(parameterNum, configFilename, frame)
#error, minTau = _tgmm_io.readConfigFile_py(parameterNum, configFilename, frame, basename, radiusMedianFilter, backgroundThr, conn3D)
#error = _tgmm_io.readConfigFile_py(parameterNum, configFilename, frame, basename, radiusMedianFilter, minTau, backgroundThr, conn3D)
print "After single_timepoint_ProcessStack "
print "error: ",error
#print "basename: ",basename
#print "radiusMedianFilter: ",radiusMedianFilter
#print "minTau: ",minTau
#print "backgroundThr: ",backgroundThr
#print "conn3D: ",conn3D
