#
# Copyright (C) 2016-2017 by  Yuan Lufeng
# See license.txt for full license and copyright notice.
#
# Authors: Yuan Lufeng 
#
# test_multiple_timepoint_TrackingGMM.py
#
#  Created on: Dec 11th, 2016
#      Author: Yuan Lufeng 
#
# \brief test tracking gaussian mixture models program for different timepoints generated by cython.
#

import _tracking_GMM  


configFilename = "/home/tgmm/ylf/TBP-tgmm/data/TGMM_configFile_linux.txt"
parameterNum = 4
begin_frame = 0
end_frame = 10 
basename = " "
radiusMedianFilter = 0
minTau = 0
backgroundThr = 0
conn3D = 0
print "configFilename: ",configFilename
print "parameterNum: ",parameterNum
print "begin_frame: ",begin_frame
print "end_frame: ",end_frame
error = _tracking_GMM.TrackingGMM_py(parameterNum, configFilename, begin_frame, end_frame)
#error, basename, radiusMedianFilter, minTau, backgroundThr, conn3D = _tgmm_io.readConfigFile_py(parameterNum, configFilename, frame)
#error, minTau = _tgmm_io.readConfigFile_py(parameterNum, configFilename, frame, basename, radiusMedianFilter, backgroundThr, conn3D)
#error = _tgmm_io.readConfigFile_py(parameterNum, configFilename, frame, basename, radiusMedianFilter, minTau, backgroundThr, conn3D)
print "After multiple_timepoint_TrackingGMM "
print "error: ",error
#print "basename: ",basename
#print "radiusMedianFilter: ",radiusMedianFilter
#print "minTau: ",minTau
#print "backgroundThr: ",backgroundThr
#print "conn3D: ",conn3D
