## 
## Copyright (C) 2016-2017 by  Yuan Lufeng
## See license.txt for full license and copyright notice.
## 
## Authors: Yuan Lufeng 
## 
## test_multiple_timepoint_ProcessStack.py
## 
##  Created on: Oct 21th, 2016
##      Author: Yuan Lufeng 
## 
## \brief test multiple timepoint ProcessStack program generated by cython.
##
##

import _process_stack  
import time

configFilename = "/home/tgmm/ylf/TBP-tgmm/data/TGMM_configFile_linux.txt"
parameterNum = 3
begin_frame = 0 
end_frame = 20 
basename = " "
radiusMedianFilter = 0
minTau = 0
backgroundThr = 0
conn3D = 0
print "configFilename: ",configFilename
print "parameterNum: ",parameterNum
start = time.time()
for frame in range(begin_frame,end_frame):
	print "frame: ",frame
	error = _process_stack.ProcessStack_py(parameterNum, configFilename, frame)
#error, basename, radiusMedianFilter, minTau, backgroundThr, conn3D = _tgmm_io.readConfigFile_py(parameterNum, configFilename, frame)
#error, minTau = _tgmm_io.readConfigFile_py(parameterNum, configFilename, frame, basename, radiusMedianFilter, backgroundThr, conn3D)
#error = _tgmm_io.readConfigFile_py(parameterNum, configFilename, frame, basename, radiusMedianFilter, minTau, backgroundThr, conn3D)
print "After T-ProcessStack "
print "error: ",error
end = time.time()
print "Sessions use time is", end - start
#print "basename: ",basename
#print "radiusMedianFilter: ",radiusMedianFilter
#print "minTau: ",minTau
#print "backgroundThr: ",backgroundThr
#print "conn3D: ",conn3D
